project:
  type: website
  # output-dir: karamel.co.uk
  output-dir: cullaloe.net

website:
  # title: "Karamel.co.uk"
  title: "sketchy stuff"
  favicon: anarchy.gif # needs to be in root directory

format:
  html:
    theme: sketchy
    # theme: cosmo
    toc: true



